import type { Vehicle } from "./types";

export const mockVehicles: Vehicle[] = [
  // Motorcycles
  {
    id: "1",
    name: "Honda PCX 160",
    brand: "Honda",
    category: "motorcycle",
    type: "scooter",
    pricePerDay: 15,
    image: "/honda-pcx-160-white-scooter-motorcycle.jpg",
    shopName: "Bali Motorbike Rental",
    shopAddress: "Jl. Sunset Road No. 88, Seminyak",
    distance: 0.8,
    openingHours: "08:00 - 20:00",
    specs: {
      engine: "160cc",
      transmission: "Automatic",
      fuelCapacity: "8.1L",
      seatHeight: "764mm",
    },
    requirements: [
      "Valid ID (KTP/Passport)",
      "Valid driving license (SIM C)",
      "Deposit: $50",
    ],
    available: true,
  },
  {
    id: "2",
    name: "Yamaha NMAX 155",
    brand: "Yamaha",
    category: "motorcycle",
    type: "scooter",
    pricePerDay: 18,
    image: "/yamaha-nmax-155-blue-scooter-motorcycle.jpg",
    shopName: "Island Riders",
    shopAddress: "Jl. Legian No. 123, Kuta",
    distance: 1.2,
    openingHours: "07:00 - 21:00",
    specs: {
      engine: "155cc",
      transmission: "Automatic",
      fuelCapacity: "7.1L",
      seatHeight: "765mm",
    },
    requirements: [
      "Valid ID (KTP/Passport)",
      "Valid driving license (SIM C)",
      "Deposit: $60",
    ],
    available: true,
  },
  {
    id: "3",
    name: "Honda Vario 160",
    brand: "Honda",
    category: "motorcycle",
    type: "scooter",
    pricePerDay: 12,
    image: "/honda-vario-160-red-scooter-motorcycle.jpg",
    shopName: "Quick Rent Bali",
    shopAddress: "Jl. Pantai Kuta No. 45, Kuta",
    distance: 2.1,
    openingHours: "08:00 - 19:00",
    specs: {
      engine: "160cc",
      transmission: "Automatic",
      fuelCapacity: "5.5L",
      seatHeight: "770mm",
    },
    requirements: [
      "Valid ID (KTP/Passport)",
      "Valid driving license (SIM C)",
      "Deposit: $40",
    ],
    available: true,
  },
  {
    id: "4",
    name: "Kawasaki Ninja 250",
    brand: "Kawasaki",
    category: "motorcycle",
    type: "sport",
    pricePerDay: 45,
    image: "/kawasaki-ninja-250-green-sport-motorcycle.jpg",
    shopName: "Premium Bike Rentals",
    shopAddress: "Jl. Bypass Ngurah Rai No. 200",
    distance: 3.5,
    openingHours: "09:00 - 18:00",
    specs: {
      engine: "249cc",
      transmission: "Manual 6-speed",
      fuelCapacity: "14L",
      seatHeight: "795mm",
    },
    requirements: [
      "Valid ID (KTP/Passport)",
      "Valid driving license (SIM C)",
      "Deposit: $200",
      "Experience required",
    ],
    available: false,
  },
  {
    id: "5",
    name: "Vespa Primavera 150",
    brand: "Vespa",
    category: "motorcycle",
    type: "scooter",
    pricePerDay: 25,
    image: "/vespa-primavera-150-classic-beige-scooter.jpg",
    shopName: "Classic Rides Bali",
    shopAddress: "Jl. Oberoi No. 77, Seminyak",
    distance: 1.8,
    openingHours: "09:00 - 20:00",
    specs: {
      engine: "150cc",
      transmission: "Automatic",
      fuelCapacity: "7L",
      seatHeight: "790mm",
    },
    requirements: [
      "Valid ID (KTP/Passport)",
      "Valid driving license (SIM C)",
      "Deposit: $100",
    ],
    available: true,
  },
  {
    id: "6",
    name: "Honda CB150R",
    brand: "Honda",
    category: "motorcycle",
    type: "naked",
    pricePerDay: 28,
    image: "/honda-cb150r-naked-streetfighter-motorcycle-red.jpg",
    shopName: "Bali Motorbike Rental",
    shopAddress: "Jl. Sunset Road No. 88, Seminyak",
    distance: 0.8,
    openingHours: "08:00 - 20:00",
    specs: {
      engine: "149cc",
      transmission: "Manual 6-speed",
      fuelCapacity: "12L",
      seatHeight: "795mm",
    },
    requirements: [
      "Valid ID (KTP/Passport)",
      "Valid driving license (SIM C)",
      "Deposit: $80",
    ],
    available: true,
  },
  // Cars
  {
    id: "7",
    name: "Toyota Avanza",
    brand: "Toyota",
    category: "car",
    type: "mpv",
    pricePerDay: 45,
    image: "/toyota-avanza-silver-mpv-car.jpg",
    shopName: "Bali Car Rental",
    shopAddress: "Jl. Sunset Road No. 100, Seminyak",
    distance: 1.0,
    openingHours: "08:00 - 20:00",
    specs: {
      engine: "1500cc",
      transmission: "Automatic",
      fuelCapacity: "45L",
      seats: 7,
    },
    requirements: [
      "Valid ID (KTP/Passport)",
      "Valid driving license (SIM A)",
      "Deposit: $100",
    ],
    available: true,
  },
  {
    id: "8",
    name: "Honda Brio",
    brand: "Honda",
    category: "car",
    type: "hatchback",
    pricePerDay: 35,
    image: "/honda-brio-white-hatchback-car.jpg",
    shopName: "Island Auto",
    shopAddress: "Jl. Legian No. 200, Kuta",
    distance: 1.5,
    openingHours: "07:00 - 21:00",
    specs: {
      engine: "1200cc",
      transmission: "Automatic",
      fuelCapacity: "35L",
      seats: 5,
    },
    requirements: [
      "Valid ID (KTP/Passport)",
      "Valid driving license (SIM A)",
      "Deposit: $80",
    ],
    available: true,
  },
  {
    id: "9",
    name: "Toyota Fortuner",
    brand: "Toyota",
    category: "car",
    type: "suv",
    pricePerDay: 95,
    image: "/toyota-fortuner-black-suv-car.jpg",
    shopName: "Premium Auto Bali",
    shopAddress: "Jl. Bypass Ngurah Rai No. 150",
    distance: 2.5,
    openingHours: "09:00 - 18:00",
    specs: {
      engine: "2400cc",
      transmission: "Automatic",
      fuelCapacity: "80L",
      seats: 7,
    },
    requirements: [
      "Valid ID (KTP/Passport)",
      "Valid driving license (SIM A)",
      "Deposit: $300",
    ],
    available: true,
  },
  {
    id: "10",
    name: "Honda City",
    brand: "Honda",
    category: "car",
    type: "sedan",
    pricePerDay: 55,
    image: "/honda-city-white-sedan-car.jpg",
    shopName: "City Car Rental",
    shopAddress: "Jl. Dewi Sri No. 50, Kuta",
    distance: 1.8,
    openingHours: "08:00 - 20:00",
    specs: {
      engine: "1500cc",
      transmission: "CVT",
      fuelCapacity: "40L",
      seats: 5,
    },
    requirements: [
      "Valid ID (KTP/Passport)",
      "Valid driving license (SIM A)",
      "Deposit: $120",
    ],
    available: false,
  },
  {
    id: "11",
    name: "Mitsubishi Xpander",
    brand: "Mitsubishi",
    category: "car",
    type: "mpv",
    pricePerDay: 50,
    image: "/mitsubishi-xpander-gray-mpv-car.jpg",
    shopName: "Bali Car Rental",
    shopAddress: "Jl. Sunset Road No. 100, Seminyak",
    distance: 1.0,
    openingHours: "08:00 - 20:00",
    specs: {
      engine: "1500cc",
      transmission: "Automatic",
      fuelCapacity: "45L",
      seats: 7,
    },
    requirements: [
      "Valid ID (KTP/Passport)",
      "Valid driving license (SIM A)",
      "Deposit: $100",
    ],
    available: true,
  },
];

export const motorcycleTypes = [
  { value: "scooter", label: "Scooter" },
  { value: "sport", label: "Sport" },
  { value: "cruiser", label: "Cruiser" },
  { value: "adventure", label: "Adventure" },
  { value: "naked", label: "Naked" },
];

export const carTypes = [
  { value: "sedan", label: "Sedan" },
  { value: "suv", label: "SUV" },
  { value: "hatchback", label: "Hatchback" },
  { value: "mpv", label: "MPV" },
  { value: "pickup", label: "Pickup" },
];
